server:
  port: 8082

spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update # Permite atualizar as tabelas automaticamente de acordo com o código
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: ALWAYS

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/'
      course: 'http://ead-course-service/'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost
